apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rabbitmq-credentials
  namespace: secureops
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: rabbitmq-credentials
    creationPolicy: Owner
  data:
    - secretKey: RABBITMQ_PASSWORD
      remoteRef:
        key: secureops/rabbitmq
