apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: db-credentials
  namespace: secureops
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: db-credentials
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        AUTH_DATABASE_URL: "postgresql://{{ .username }}:{{ .password }}@secureops-postgres.cwzswq2q46jc.us-east-1.rds.amazonaws.com:5432/secureops_auth_db"
        DATABASE_URL: "postgresql://{{ .username }}:{{ .password }}@secureops-postgres.cwzswq2q46jc.us-east-1.rds.amazonaws.com:5432/secureops_db"
  dataFrom:
    - extract:
        key: secureops/database
