apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification
  namespace: secureops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification
  template:
    metadata:
      labels:
        app: notification
    spec:
      containers:
        - name: notification
          image: 265404808693.dkr.ecr.us-east-1.amazonaws.com/secureops/notification:init
          env:
            - name: SLACK_WEBHOOK_URL
              valueFrom:
                secretKeyRef:
                  name: notification-credentials
                  key: SLACK_WEBHOOK_URL
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-credentials
                  key: RABBITMQ_PASSWORD
            - name: RABBITMQ_URL
              value: "amqp://secureops:$(RABBITMQ_PASSWORD)@rabbitmq:5672/"
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
