apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: rabbitmq
  namespace: secureops
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: rabbitmq
  endpoints:
    - port: metrics
      interval: 30s
