apiVersion: apps/v1
kind: Deployment
metadata:
  name: response
  namespace: secureops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: response
  template:
    metadata:
      labels:
        app: response
        secureops.io/critical-infra: "true"
    spec:
      serviceAccountName: response-sa
      containers:
        - name: response
          image: 265404808693.dkr.ecr.us-east-1.amazonaws.com/secureops/response:21e2b24f37b5e0b061008dc849dcf995f350444e
          env:
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-credentials
                  key: RABBITMQ_PASSWORD
            - name: RABBITMQ_URL
              value: "amqp://secureops:$(RABBITMQ_PASSWORD)@rabbitmq:5672/"
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
